### ISSUE TITLE
doesnt respect interval and it jumps

### ISSUE THREAD

**Issue by neuropass** [alihaddadkar/bear-slideshow#1]
Looks like it does not respect the interval time and it also jumps all the sudden to another picture. 
Firefox , win10.

**Comment by alihaddadkar** [comment]
Hello.
Do you have problem only in firefox, win10?
Thanks for report issue.

**Comment by neuropass** [comment]
Tested on edge and chrome and exact same two issues.

**Comment by alihaddadkar** [comment]
Can you give me screen video capture from slideshow?

**Comment by alihaddadkar** [comment]
Problem solved.
